### ISSUE TITLE
IpSupport issues could be represented by capabilites

### ISSUE THREAD

**Issue by binod33** [dasein-cloud/dasein-cloud-core#16]
Some clouds like azure and azure pack seems to have partial support for IpAddresses and  dasien seems to be returning no support in such cases. If there were some more nuanced capabilities to determine this behavior of partial support, maybe dasein can then open support for IpAddresses for such clouds?

**Comment by drewlyall** [comment]
It's really a hack to allow some slightly awkwardly mapped methods for those situations.
Really we should turn on IpAddressSupport in the Services class and have all the other methods throw OperationNotSupported methods.
I'm not comfortable having a series of capabilities to essentially "turn off" those methods...
I guess I could be convinced otherwise.
