### ISSUE TITLE
RDP port for windows servers

### ISSUE THREAD

**Issue by binod33** [dasein-cloud/dasein-cloud-core#21]
Clouds like azure has a different RDP port than usual default for accessing windows vm.
usual default for other clouds  = 3389 but for azure it is = 58622 
A method to extract the cloud specific RDP port value would be helpful.
Probably same for SSH ports if applicable?

**Comment by drewlyall** [comment]
Actually it's not fixed in Azure. Dasein hardcodes it at the moment to make it a bit easier but any Azure endpoint created with an auto selected port could have anything in the top end of the 50,000 range.
There's a method "listRulesForServer" which will allow you to check the forwarding rules in place and get the public RDP port from there.
